# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('Project_1_ANN_Banking.csv')
X = dataset.iloc[:, 3:-1].values #Printing starting from index 3(CreditScore) to EstimatedSalary excluding -1(Exited)--->Train Attributes 
y = dataset.iloc[:, -1].values #Printing only last column Exited--->Target Attribute

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


### Encoding categorical data

In [9]:
Label Encoding the "Gender" column

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2]) #Encoding index 2 column only(Gender)

In [11]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') #[1]--->Column index 1
X = np.array(ct.fit_transform(X))

In [14]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) #0.2--->20% data from train data set will be tested

### Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
#Scaling everything

## Part 2 - Building the ANN

### Initializing the ANN

In [17]:
ann = tf.keras.models.Sequential() #Initializing ANN as a sequence of layers

### Adding the input layer and the first hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #Automatically add input neorons,assuming 6 neurons in first hidden layer

### Adding the second hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [21]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) #For probability of binary outcome & prediction sigmoid preferable,Output layer 1

## Part 3 - Training the ANN

### Compiling the ANN

In [22]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#adam--->updating weights to reduce loss through iteration
#loss--->compute difference between prediction & real result
#binary_crossentrophy--->Always be for binary classification & for non-binary it will be catagorical_crossentrophy

### Training the ANN on the Training set

In [23]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100) 

Epoch 1/100
250/250 [==============================] - 4s 7ms/step - loss: 0.6375 - accuracy: 0.6315
Epoch 2/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4646 - accuracy: 0.7959
Epoch 3/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4301 - accuracy: 0.8083
Epoch 4/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4148 - accuracy: 0.8161
Epoch 5/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4001 - accuracy: 0.8248
Epoch 6/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3846 - accuracy: 0.8351
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3722 - accuracy: 0.8426
Epoch 8/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3649 - accuracy: 0.8454
Epoch 9/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3615 - accuracy: 0.8468
Epoch 10/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3599 - accura

250/250 [==============================] - 2s 6ms/step - loss: 0.3362 - accuracy: 0.8644
Epoch 82/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3363 - accuracy: 0.8633
Epoch 83/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3358 - accuracy: 0.8631
Epoch 84/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3369 - accuracy: 0.8633
Epoch 85/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3359 - accuracy: 0.8656
Epoch 86/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3361 - accuracy: 0.8624
Epoch 87/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3363 - accuracy: 0.8646
Epoch 88/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3355 - accuracy: 0.8656
Epoch 89/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3361 - accuracy: 0.8625
Epoch 90/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3359 - accuracy: 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Solution**

In [25]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5) #predicting desired train data
#False means value is close to zero--->means customer eill stay according to target dataset

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [26]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
#Comparing between predicting result(0 column) vs real result(1 column)

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)
#Confusion matrix--->Finding accuracy
#1516 correct prediction-Customer stays in the bank,205 leaves from the bank & 79 inaccurate prediction-Customer leaves from the bank,200 -Customer stays in the bank

[[1526   69]
 [ 205  200]]


0.863